apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-jbrr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rsoaresd_org/rs-demos-dipo-tenant/image-repository-cr-dotnet-component/devfile-sample-dotnet60-basic-jbrr@sha256:42433da0c691a171530939aa3ea6498925dd7696416f767b4790c58926554fa7
        name: main
        resources: {}
status: {}
