apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-jbrr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-jbrr
    app.kubernetes.io/part-of: image-repository-cr-dotnet-component
  name: devfile-sample-dotnet60-basic-jbrr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-jbrr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-jbrr
    spec:
      containers:
      - image: quay.io/rsoaresd_org/rs-demos-dipo-tenant/image-repository-cr-dotnet-component/devfile-sample-dotnet60-basic-jbrr@sha256:42433da0c691a171530939aa3ea6498925dd7696416f767b4790c58926554fa7
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
